<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ITLTools\ITLTools.csproj" />
    <ProjectReference Include="..\MusicFileUtilities\MusicFileUtilities.csproj" />
  </ItemGroup>
</Project>
