<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net60-windows</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
	<ItemGroup>
		<SupportedPlatform Include="Windows" />
	</ItemGroup>
	<ItemGroup>
    <COMReference Include="iTunesLib">
      <Guid>{9E93C96F-CF0D-43F6-8BA8-B807A3370712}</Guid>
      <VersionMajor>1</VersionMajor>
      <VersionMinor>13</VersionMinor>
      <Lcid>0</Lcid>
      <WrapperTool>tlbimp</WrapperTool>
      <Isolated>False</Isolated>
      <EmbedInteropTypes>True</EmbedInteropTypes>
    </COMReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MusicFileUtilities\MusicFileUtilities.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.1" />
  </ItemGroup>
</Project>