<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>MusicLibraryManager</RootNamespace>
    <AssemblyName>MusicLibraryManager</AssemblyName>
    <ApplicationIcon>Assets\AppIcon.ico</ApplicationIcon>
    <Copyright>Copyright (c) 2010-2026 Colin Hill</Copyright>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
    <CopyDebugSymbolFilesFromPackages>false</CopyDebugSymbolFilesFromPackages>
    <CopyDocumentationFilesFromPackages>false</CopyDocumentationFilesFromPackages>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\AppIcon.ico" />
    <AvaloniaResource Include="Assets\Licenses\AvaloniaUI-12.1.0-MIT.txt" />
    <AvaloniaResource Include="Assets\Licenses\SkiaSharp-4.150.1-MIT.txt" />
    <AvaloniaResource Include="Assets\Licenses\SkiaSharp-4.150.1-THIRD-PARTY-NOTICES.txt" />
    <None Update="SETTINGS_REFERENCE.md"
          CopyToPublishDirectory="PreserveNewest" />
    <None Update="Assets\Licenses\AvaloniaUI-12.1.0-MIT.txt"
          CopyToPublishDirectory="PreserveNewest"
          TargetPath="ThirdPartyLicenses\AvaloniaUI-12.1.0-MIT.txt" />
    <None Update="Assets\Licenses\SkiaSharp-4.150.1-MIT.txt"
          CopyToPublishDirectory="PreserveNewest"
          TargetPath="ThirdPartyLicenses\SkiaSharp-4.150.1-MIT.txt" />
    <None Update="Assets\Licenses\SkiaSharp-4.150.1-THIRD-PARTY-NOTICES.txt"
          CopyToPublishDirectory="PreserveNewest"
          TargetPath="ThirdPartyLicenses\SkiaSharp-4.150.1-THIRD-PARTY-NOTICES.txt" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Controls.DataGrid" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <ProjectReference Include="..\MusicLibrary.Core\MusicLibrary.Core.csproj" />
    <ProjectReference Include="..\MusicLibraryManager.Presentation\MusicLibraryManager.Presentation.csproj" />
  </ItemGroup>
</Project>
