<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net80-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <COMReference Include="iTunesLib">
      <WrapperTool>tlbimp</WrapperTool>
      <VersionMinor>13</VersionMinor>
      <VersionMajor>1</VersionMajor>
      <Guid>9e93c96f-cf0d-43f6-8ba8-b807a3370712</Guid>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
      <EmbedInteropTypes>true</EmbedInteropTypes>
    </COMReference>
  </ItemGroup>

</Project>
