<#
.SYNOPSIS
  Generates the media fixtures used by the MusicFileUtilities tests.

  Run automatically at build time by a target in MusicFileUtilities.Tests.csproj, so the
  binary fixtures are produced by the toolchain rather than committed to the repo.

  The audio formats come from ffmpeg (mostly 0.3s 44.1kHz/16-bit/stereo tone clips tagged with
  a fixed baseline). The .dsf file is hand-crafted here because no DSD encoder is bundled;
  it is a minimal-but-valid DSF container (DSD64, stereo, 1-bit) with no metadata chunk, so
  the DSF tag-write path is exercised by the tests writing tags into it. The Monkey's Audio
  fixture is a structural 3.99 stream because ffmpeg provides a decoder but no APE encoder.
  Musepack and TAK likewise use compact reference-demuxable structural streams. OptimFROG uses
  committed reference streams generated by the official 5.100 command-line tools because those
  proprietary encoders are not available on ordinary developer or CI machines.
#>
param(
    [Parameter(Mandatory = $true)][string]$OutDir,
    [switch]$RegenerateOptimFrog,
    [string]$OptimFrogTools
)

$ErrorActionPreference = 'Stop'

New-Item -ItemType Directory -Force -Path $OutDir | Out-Null

function Resolve-Ffmpeg {
    $cmd = Get-Command ffmpeg -ErrorAction SilentlyContinue
    if ($cmd) { return $cmd.Source }
    foreach ($p in @('C:\ffmpeg\bin\ffmpeg.exe', 'C:\Program Files\ffmpeg\bin\ffmpeg.exe')) {
        if (Test-Path $p) { return $p }
    }
    throw "ffmpeg not found on PATH or in known locations. Install ffmpeg to generate test fixtures."
}

function Resolve-VorbisEncoderArgs {
    param([Parameter(Mandatory = $true)][string]$Ffmpeg)

    $encoders = (& $Ffmpeg -hide_banner -encoders 2>&1) | Out-String
    if ($LASTEXITCODE -ne 0) { throw "ffmpeg failed while listing available encoders." }

    if ($encoders -match '(?m)^\s*A\S{5}\s+libvorbis\s') {
        return @('-c:a', 'libvorbis')
    }
    if ($encoders -match '(?m)^\s*A\S{5}\s+vorbis\s') {
        # FFmpeg's built-in Vorbis encoder is marked experimental in current releases.
        return @('-c:a', 'vorbis', '-strict', 'experimental')
    }

    throw "ffmpeg provides neither the libvorbis nor native Vorbis audio encoder."
}

function Resolve-OptimFrogTools {
    $roots = @()
    if (-not [string]::IsNullOrWhiteSpace($OptimFrogTools)) {
        $roots += $OptimFrogTools
    }
    $roots += Join-Path (Split-Path $PSScriptRoot -Parent) `
        '.artifacts\tools\optimfrog\5.100\win-x64\OptimFROG_Win_x64_5100'

    foreach ($root in $roots) {
        $ofr = Join-Path $root 'ofr.exe'
        $ofs = Join-Path $root 'ofs.exe'
        $off = Join-Path $root 'off.exe'
        if ((Test-Path $ofr) -and (Test-Path $ofs) -and (Test-Path $off)) {
            return [pscustomobject]@{ Ofr = $ofr; Ofs = $ofs; Off = $off }
        }
    }

    $ofrCommand = Get-Command ofr.exe -ErrorAction SilentlyContinue
    $ofsCommand = Get-Command ofs.exe -ErrorAction SilentlyContinue
    $offCommand = Get-Command off.exe -ErrorAction SilentlyContinue
    if ($ofrCommand -and $ofsCommand -and $offCommand) {
        return [pscustomobject]@{
            Ofr = $ofrCommand.Source
            Ofs = $ofsCommand.Source
            Off = $offCommand.Source
        }
    }

    throw "OptimFROG 5.100 tools were not found. Pass -OptimFrogTools or extract the official package under .artifacts/tools/optimfrog."
}

# --- ffmpeg-encoded fixtures ----------------------------------------------------------------
$meta = @(
    '-metadata', 'title=TestTitle',
    '-metadata', 'artist=TestArtist',
    '-metadata', 'album=TestAlbum',
    '-metadata', 'date=2021',
    '-metadata', 'genre=Rock',
    '-metadata', 'track=3'
)
$sine = @('-f', 'lavfi', '-i', 'sine=frequency=440:duration=0.3', '-ac', '2', '-ar', '44100')

$jobs = @(
    @{ File = 'sample.flac';      Args = @('-sample_fmt', 's16') + $meta },
    @{ File = 'sample.mp3';       Args = @('-c:a', 'libmp3lame', '-b:a', '128k', '-write_xing', '1', '-id3v2_version', '3') + $meta },
    @{ File = 'sample.ogg';       Args = $null },
    @{ File = 'sample_alac.m4a';  Args = @('-c:a', 'alac') + $meta },
    @{ File = 'sample_aac.m4a';   Args = @('-c:a', 'aac', '-b:a', '128k') + $meta },
    @{ File = 'sample.wv';        Args = @('-c:a', 'wavpack') + $meta },
    @{ File = 'sample.wav';       Args = @('-c:a', 'pcm_s16le') + $meta },
    @{ File = 'sample.aiff';      Args = @('-c:a', 'pcm_s16be') + $meta },
    @{ File = 'sample.aac';       Args = @('-c:a', 'aac', '-b:a', '128k', '-f', 'adts') },
    @{ File = 'sample.tta';       Args = @('-c:a', 'tta') + $meta },
    @{ File = 'sample.wma';       Args = @('-c:a', 'wmav2', '-b:a', '64k') + $meta }
)

$needFfmpeg = $jobs | Where-Object { -not (Test-Path (Join-Path $OutDir $_.File)) }
if ($needFfmpeg) {
    $ffmpeg = Resolve-Ffmpeg
    $oggJob = $needFfmpeg | Where-Object { $_.File -eq 'sample.ogg' }
    if ($oggJob) {
        $oggJob.Args = @(Resolve-VorbisEncoderArgs -Ffmpeg $ffmpeg) + $meta
    }
    foreach ($j in $needFfmpeg) {
        $out = Join-Path $OutDir $j.File
        & $ffmpeg -y -hide_banner -loglevel error @sine @($j.Args) $out
        if ($LASTEXITCODE -ne 0) { throw "ffmpeg failed for $($j.File)" }
    }
}

# Additional quality/channel fixtures used by ingest policy tests.
$specialJobs = @(
    @{
        File = 'sample_hires.flac'
        Input = @('-f', 'lavfi', '-i', 'sine=frequency=440:duration=0.3', '-ac', '2', '-ar', '96000')
        Args = @('-sample_fmt', 's32') + $meta
    },
    @{
        File = 'sample_multi.flac'
        Input = @('-f', 'lavfi', '-i', 'anullsrc=r=48000:cl=5.1:d=0.3')
        Args = @('-sample_fmt', 's32') + $meta
    }
)
$needSpecial = $specialJobs | Where-Object { -not (Test-Path (Join-Path $OutDir $_.File)) }
if ($needSpecial) {
    $ffmpeg = Resolve-Ffmpeg
    foreach ($j in $needSpecial) {
        $out = Join-Path $OutDir $j.File
        & $ffmpeg -y -hide_banner -loglevel error @($j.Input) @($j.Args) $out
        if ($LASTEXITCODE -ne 0) { throw "ffmpeg failed for $($j.File)" }
    }
}

# --- hand-crafted Monkey's Audio fixture ----------------------------------------------------
function New-ApeV2Tag {
    $entries = [ordered]@{
        Title  = 'TestTitle'
        Artist = 'TestArtist'
        Album  = 'TestAlbum'
        Genre  = 'Rock'
        Track  = '3'
    }
    $ascii = [System.Text.Encoding]::ASCII
    $utf8 = [System.Text.UTF8Encoding]::new($false)
    $itemsStream = [System.IO.MemoryStream]::new()
    $itemsWriter = [System.IO.BinaryWriter]::new($itemsStream)
    foreach ($entry in $entries.GetEnumerator()) {
        [byte[]]$keyBytes = $ascii.GetBytes([string]$entry.Key)
        [byte[]]$valueBytes = $utf8.GetBytes([string]$entry.Value)
        $itemsWriter.Write([uint32]$valueBytes.Length)
        $itemsWriter.Write([uint32]0)
        $itemsWriter.Write($keyBytes)
        $itemsWriter.Write([byte]0)
        $itemsWriter.Write($valueBytes)
    }
    $itemsWriter.Flush()
    [byte[]]$items = $itemsStream.ToArray()
    $itemsWriter.Dispose()
    $itemsStream.Dispose()

    $tagStream = [System.IO.MemoryStream]::new()
    $tagWriter = [System.IO.BinaryWriter]::new($tagStream)
    [uint32]$tagSize = $items.Length + 32
    foreach ($flags in @([uint32]2684354560, [uint32]2147483648)) {
        $tagWriter.Write($ascii.GetBytes('APETAGEX'))
        $tagWriter.Write([uint32]2000)
        $tagWriter.Write($tagSize)
        $tagWriter.Write([uint32]$entries.Count)
        $tagWriter.Write($flags)
        $tagWriter.Write([uint64]0)
        if ($flags -eq [uint32]2684354560) {
            $tagWriter.Write($items)
        }
    }
    $tagWriter.Flush()
    [byte[]]$result = $tagStream.ToArray()
    $tagWriter.Dispose()
    $tagStream.Dispose()
    return ,$result
}

$apePath = Join-Path $OutDir 'sample.ape'
if (-not (Test-Path $apePath)) {
    $ms = [System.IO.MemoryStream]::new()
    $bw = [System.IO.BinaryWriter]::new($ms)
    $ascii = [System.Text.Encoding]::ASCII

    # Descriptor-based Monkey's Audio 3.99 header.
    $bw.Write($ascii.GetBytes('MAC '))
    $bw.Write([uint16]3990)
    $bw.Write([uint16]0)
    $bw.Write([uint32]52)       # descriptor length
    $bw.Write([uint32]24)       # header length
    $bw.Write([uint32]4)        # one seek-table entry
    $bw.Write([uint32]0)        # stored WAVE header length
    $bw.Write([uint32]64)       # compressed audio length
    $bw.Write([uint32]0)        # compressed audio length high
    $bw.Write([uint32]0)        # WAVE tail length
    $bw.Write([byte[]]::new(16))

    $bw.Write([uint16]2000)     # normal compression
    $bw.Write([uint16]0)        # format flags
    $bw.Write([uint32]73728)    # blocks per frame
    $bw.Write([uint32]13230)    # final frame blocks (0.3 seconds)
    $bw.Write([uint32]1)        # total frames
    $bw.Write([uint16]16)
    $bw.Write([uint16]2)
    $bw.Write([uint32]44100)
    $bw.Write([uint32]80)       # first frame offset
    $bw.Write([byte[]](0..63 | ForEach-Object {
        [byte](($_ * 37 + 11) % 251)
    }))
    [byte[]]$tag = New-ApeV2Tag
    $bw.Write($tag)

    $bw.Flush()
    [System.IO.File]::WriteAllBytes($apePath, $ms.ToArray())
    $bw.Dispose()
    $ms.Dispose()
}

# --- hand-crafted Musepack and TAK fixtures ------------------------------------------------
$mpcPath = Join-Path $OutDir 'sample.mpc'
if (-not (Test-Path $mpcPath)) {
    $ms = [System.IO.MemoryStream]::new()
    $bw = [System.IO.BinaryWriter]::new($ms)
    $bw.Write([System.Text.Encoding]::ASCII.GetBytes('MP+'))
    $bw.Write([byte]7)
    $bw.Write([uint32]12)        # twelve 1152-sample SV7 frames
    [byte[]]$extra = [byte[]]::new(16)
    $extra[2] = 0                # 44.1 kHz sample-rate index
    $bw.Write($extra)
    $bw.Write([byte[]](0..95 | ForEach-Object {
        [byte](($_ * 13 + 7) % 251)
    }))
    [byte[]]$tag = New-ApeV2Tag
    $bw.Write($tag)
    $bw.Flush()
    [System.IO.File]::WriteAllBytes($mpcPath, $ms.ToArray())
    $bw.Dispose()
    $ms.Dispose()
}

function New-TakStreamInfo {
    $fields = @(
        @([uint64]2, 6),          # mono/stereo codec
        @([uint64]0, 4),          # profile
        @([uint64]4, 4),          # 4096-sample frame type
        @([uint64]13230, 35),     # sample count
        @([uint64]0, 3),          # integer sample data
        @([uint64](44100 - 6000), 18),
        @([uint64](16 - 8), 5),
        @([uint64](2 - 1), 4),
        @([uint64]0, 1)           # no extended channel layout
    )
    [int]$totalBits = ($fields | ForEach-Object { $_[1] } |
        Measure-Object -Sum).Sum
    [byte[]]$result = [byte[]]::new([int][Math]::Ceiling($totalBits / 8.0))
    $bitOffset = 0
    foreach ($field in $fields) {
        [uint64]$value = $field[0]
        [int]$count = $field[1]
        for ($bit = 0; $bit -lt $count; $bit++) {
            if (($value -band ([uint64]1 -shl $bit)) -ne 0) {
                $byteIndex = [int][Math]::Floor(($bitOffset + $bit) / 8.0)
                $bitIndex = ($bitOffset + $bit) % 8
                $result[$byteIndex] = $result[$byteIndex] -bor (1 -shl $bitIndex)
            }
        }
        $bitOffset += $count
    }
    return ,$result
}

$takPath = Join-Path $OutDir 'sample.tak'
if (-not (Test-Path $takPath)) {
    $ms = [System.IO.MemoryStream]::new()
    $bw = [System.IO.BinaryWriter]::new($ms)
    $bw.Write([System.Text.Encoding]::ASCII.GetBytes('tBaK'))
    [byte[]]$info = New-TakStreamInfo
    [int]$blockSize = $info.Length + 3
    $bw.Write([byte]1)            # TAK_METADATA_STREAMINFO
    $bw.Write([byte]($blockSize -band 0xff))
    $bw.Write([byte](($blockSize -shr 8) -band 0xff))
    $bw.Write([byte](($blockSize -shr 16) -band 0xff))
    $bw.Write($info)
    $bw.Write([byte[]]::new(3))   # CRC24; parser validates bounds, not checksum
    $bw.Write([byte]0)            # TAK_METADATA_END
    $bw.Write([byte[]]::new(3))
    $bw.Write([byte[]](0..95 | ForEach-Object {
        [byte](($_ * 29 + 3) % 251)
    }))
    [byte[]]$tag = New-ApeV2Tag
    $bw.Write($tag)
    $bw.Flush()
    [System.IO.File]::WriteAllBytes($takPath, $ms.ToArray())
    $bw.Dispose()
    $ms.Dispose()
}

# --- official OptimFROG 5.100 reference fixtures -------------------------------------------
$optimFrogReferences = Join-Path $PSScriptRoot 'ReferenceFixtures\OptimFROG'
if ($RegenerateOptimFrog) {
    $tools = Resolve-OptimFrogTools
    $ffmpeg = Resolve-Ffmpeg
    New-Item -ItemType Directory -Force -Path $optimFrogReferences | Out-Null
    $integerWav = Join-Path $OutDir ".optimfrog-integer-$([guid]::NewGuid().ToString('N')).wav"
    $floatWav = Join-Path $OutDir ".optimfrog-float-$([guid]::NewGuid().ToString('N')).wav"
    try {
        & $ffmpeg -y -hide_banner -loglevel error @sine -c:a pcm_s16le $integerWav
        if ($LASTEXITCODE -ne 0) { throw "ffmpeg failed to create the OptimFROG integer source." }
        & $ffmpeg -y -hide_banner -loglevel error @sine -c:a pcm_f32le $floatWav
        if ($LASTEXITCODE -ne 0) { throw "ffmpeg failed to create the OptimFROG float source." }

        $ofrReference = Join-Path $optimFrogReferences 'sample.ofr'
        $ofsReference = Join-Path $optimFrogReferences 'sample.ofs'
        $offReference = Join-Path $optimFrogReferences 'sample.off'
        foreach ($path in @($ofrReference, $ofsReference, $offReference, "$offReference.ofr")) {
            Remove-Item -LiteralPath $path -Force -ErrorAction SilentlyContinue
        }

        & $tools.Ofr --encode $integerWav --output $ofrReference
        if ($LASTEXITCODE -ne 0) { throw "OptimFROG Lossless fixture encoding failed." }
        & $tools.Ofs --encode $integerWav --output $ofsReference
        if ($LASTEXITCODE -ne 0) { throw "OptimFROG DualStream fixture encoding failed." }
        & $tools.Off --encode $floatWav --output $offReference
        if ($LASTEXITCODE -ne 0) { throw "OptimFROG Float fixture encoding failed." }
        if (-not (Test-Path $offReference) -and (Test-Path "$offReference.ofr")) {
            Move-Item -LiteralPath "$offReference.ofr" -Destination $offReference
        }

        [byte[]]$optimFrogTag = New-ApeV2Tag
        foreach ($path in @($ofrReference, $ofsReference, $offReference)) {
            if (-not (Test-Path $path)) {
                throw "OptimFROG did not create expected fixture '$path'."
            }
            $tagStream = [System.IO.File]::Open(
                $path,
                [System.IO.FileMode]::Append,
                [System.IO.FileAccess]::Write,
                [System.IO.FileShare]::None)
            try {
                $tagStream.Write($optimFrogTag, 0, $optimFrogTag.Length)
            }
            finally {
                $tagStream.Dispose()
            }
        }
    }
    finally {
        Remove-Item -LiteralPath $integerWav -Force -ErrorAction SilentlyContinue
        Remove-Item -LiteralPath $floatWav -Force -ErrorAction SilentlyContinue
    }
}

foreach ($name in @('sample.ofr', 'sample.ofs', 'sample.off')) {
    $reference = Join-Path $optimFrogReferences $name
    if (-not (Test-Path $reference)) {
        throw "Required official OptimFROG fixture is missing: $reference. Regenerate it with -RegenerateOptimFrog."
    }
    Copy-Item -LiteralPath $reference -Destination (Join-Path $OutDir $name) -Force
}

# --- hand-crafted DSF fixture ---------------------------------------------------------------
$dsfPath = Join-Path $OutDir 'sample.dsf'
if (-not (Test-Path $dsfPath)) {
    $channels      = 2
    $blockPerChan  = 4096
    $samplingFreq  = 2822400      # DSD64
    $bitsPerSample = 1
    $dataPayload   = $channels * $blockPerChan         # one block per channel
    $sampleCount   = [uint64]($blockPerChan * 8)       # bits per channel

    $dsdChunkSize  = [uint64]28
    $fmtChunkSize  = [uint64]52
    $dataChunkSize = [uint64](12 + $dataPayload)       # 'data' + size(8) + payload
    $totalSize     = [uint64](28 + 52 + 12 + $dataPayload)

    $ms = New-Object System.IO.MemoryStream
    $bw = New-Object System.IO.BinaryWriter($ms)
    $ascii = [System.Text.Encoding]::ASCII

    # DSD chunk
    $bw.Write($ascii.GetBytes('DSD '))
    $bw.Write($dsdChunkSize)
    $bw.Write($totalSize)
    $bw.Write([uint64]0)                # metadata pointer = 0 (no tag yet)

    # fmt chunk
    $bw.Write($ascii.GetBytes('fmt '))
    $bw.Write($fmtChunkSize)
    $bw.Write([uint32]1)                # format version
    $bw.Write([uint32]0)                # format id (DSD raw)
    $bw.Write([uint32]2)                # channel type (stereo)
    $bw.Write([uint32]$channels)        # channel num
    $bw.Write([uint32]$samplingFreq)
    $bw.Write([uint32]$bitsPerSample)
    $bw.Write([uint64]$sampleCount)
    $bw.Write([uint32]$blockPerChan)
    $bw.Write([uint32]0)                # reserved

    # data chunk (0x69 is DSD silence)
    $bw.Write($ascii.GetBytes('data'))
    $bw.Write($dataChunkSize)
    $bw.Write((,[byte]0x69 * $dataPayload))

    $bw.Flush()
    [System.IO.File]::WriteAllBytes($dsfPath, $ms.ToArray())
    $bw.Dispose(); $ms.Dispose()
}

Write-Host "Test fixtures ready in $OutDir"
