<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net472;netcoreapp3.1</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Data.SQLite.Core" Version="1.0.113.1" />
    <PackageReference Include="System.Text.Encoding.CodePages" Version="4.7.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MetadataCaching\MetadataCaching.csproj" />
    <ProjectReference Include="..\MusicFileUtilities\MusicFileUtilities.csproj" />
  </ItemGroup>

</Project>
