<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net80</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MetadataCaching\MetadataCaching.csproj" />
    <ProjectReference Include="..\MusicFileUtilities\MusicFileUtilities.csproj" />
  </ItemGroup>

</Project>
